[2020-09-03 00:20:27,506] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: alt_ingestion_pipeline.populate_transaction_tables 2020-09-03T04:20:11.484899+00:00 [queued]>
[2020-09-03 00:20:27,549] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: alt_ingestion_pipeline.populate_transaction_tables 2020-09-03T04:20:11.484899+00:00 [queued]>
[2020-09-03 00:20:27,549] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-09-03 00:20:27,549] {taskinstance.py:881} INFO - Starting attempt 1 of 2
[2020-09-03 00:20:27,549] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-09-03 00:20:27,579] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): populate_transaction_tables> on 2020-09-03T04:20:11.484899+00:00
[2020-09-03 00:20:27,603] {standard_task_runner.py:54} INFO - Started process 1523 to run task
[2020-09-03 00:20:27,773] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'alt_ingestion_pipeline', 'populate_transaction_tables', '2020-09-03T04:20:11.484899+00:00', '--job_id', '19', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/alt_ingestion_pipeline.py', '--cfg_path', '/tmp/tmp2a_xn9q7']
[2020-09-03 00:20:27,774] {standard_task_runner.py:78} INFO - Job 19: Subtask populate_transaction_tables
[2020-09-03 00:20:27,864] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: alt_ingestion_pipeline.populate_transaction_tables 2020-09-03T04:20:11.484899+00:00 [running]> MSI.localdomain
[2020-09-03 00:30:21,225] {logging_mixin.py:112} INFO - Some error encountered ... at :  1
[2020-09-03 00:30:21,225] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-09-03 00:30:21,258] {taskinstance.py:1070} INFO - Marking task as SUCCESS.dag_id=alt_ingestion_pipeline, task_id=populate_transaction_tables, execution_date=20200903T042011, start_date=20200903T042027, end_date=20200903T043021
[2020-09-03 00:30:25,533] {local_task_job.py:102} INFO - Task exited with return code 0
