[2020-09-03 00:15:09,290] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: alt_ingestion_pipeline.populate_transaction_tables 2020-09-03T04:13:49.830277+00:00 [queued]>
[2020-09-03 00:15:09,329] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: alt_ingestion_pipeline.populate_transaction_tables 2020-09-03T04:13:49.830277+00:00 [queued]>
[2020-09-03 00:15:09,329] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-09-03 00:15:09,329] {taskinstance.py:881} INFO - Starting attempt 1 of 2
[2020-09-03 00:15:09,329] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-09-03 00:15:09,357] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): populate_transaction_tables> on 2020-09-03T04:13:49.830277+00:00
[2020-09-03 00:15:09,380] {standard_task_runner.py:54} INFO - Started process 31820 to run task
[2020-09-03 00:15:09,560] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'alt_ingestion_pipeline', 'populate_transaction_tables', '2020-09-03T04:13:49.830277+00:00', '--job_id', '13', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/alt_ingestion_pipeline.py', '--cfg_path', '/tmp/tmpsv8xmjeg']
[2020-09-03 00:15:09,561] {standard_task_runner.py:78} INFO - Job 13: Subtask populate_transaction_tables
[2020-09-03 00:15:09,659] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: alt_ingestion_pipeline.populate_transaction_tables 2020-09-03T04:13:49.830277+00:00 [running]> MSI.localdomain
[2020-09-03 00:16:04,623] {local_task_job.py:159} WARNING - State of this instance has been externally set to failed. Taking the poison pill.
[2020-09-03 00:16:04,640] {helpers.py:325} INFO - Sending Signals.SIGTERM to GPID 31820
[2020-09-03 00:16:04,640] {taskinstance.py:955} ERROR - Received SIGTERM. Terminating subprocesses.
[2020-09-03 00:16:04,641] {logging_mixin.py:112} INFO - Some error encountered ... at :  1
[2020-09-03 00:16:04,642] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-09-03 00:16:04,693] {taskinstance.py:1070} INFO - Marking task as SUCCESS.dag_id=alt_ingestion_pipeline, task_id=populate_transaction_tables, execution_date=20200903T041349, start_date=20200903T041509, end_date=20200903T041604
[2020-09-03 00:16:04,778] {helpers.py:291} INFO - Process psutil.Process(pid=31820, status='terminated', exitcode=0, started='00:15:09') (31820) terminated with exit code 0
[2020-09-03 00:16:04,780] {helpers.py:291} INFO - Process psutil.Process(pid=32252, status='terminated', started='00:15:59') (32252) terminated with exit code None
[2020-09-03 00:16:04,781] {local_task_job.py:102} INFO - Task exited with return code 0
